### ISSUE TITLE
Prefer `Result` types over throwing errors

### ISSUE THREAD

**Issue by Stefanuk12** [strawbberrys/getnamecallmethod#1]
Throwing errors and catching with `pcall` is a lot less ergonomic and can cause performance issues when used in hooks that are called often. Instead, a `Result` type should be used.

This is in reference to use usage of `assert` mainly [here](https://github.com/strawbberrys/getnamecallmethod/blob/main/src/namecallHandlers.lua#L30). However, the `getNamecallMethod` could also be adapted to use the `Result` pattern as well.

**Comment by strawbberrys** [comment]
I think that the usage of `assert` you linked is justified. For one, if a namecall handler can't be found then the entire functionality of the script will be broken, and two, `assert` is only called once for each `getNamecallHandlerFromObject` call only when the script is first initialized and then never again, so I don't understand how this could be causing performance issues. I also don't see why using a Result would make it more ergonomic in this case since those functions are not exposed to the end-user.

I do see how it could possibly cause performance issues where it's used in the `getNamecallMethod` function, but I still think adding a Result would be redundant because this function should never fail. Is there any scenario you know about where this function could fail and there could be reason to add a Result response, because I think it might be better to just remove the check entirely and replace it with a simple if statement.

**Comment by Stefanuk12** [comment]
nah i read code wrong initially, it's probably fine to keep it as is, mb
